In [2]:
import numpy as np


In [4]:
a = np.array([0, 1, 2])
print(type(a))
print(a)
print(a.dtype)


<class 'numpy.ndarray'>
[0 1 2]
int64


In [6]:
b = np.array([1, 1.5, 2])
print(b)
print(b.dtype)

c = np.array([1 + 2j, 3 + 4j, 5 + 6j])
print(c)
print(c.dtype)

d = np.array([True, False, True, False, False])
print(d)
print(d.dtype)

e = np.array(list("TechAcademy"))
print(e)
print(e.dtype)


[1.  1.5 2. ]
float64
[1.+2.j 3.+4.j 5.+6.j]
complex128
[ True False  True False False]
bool
['T' 'e' 'c' 'h' 'A' 'c' 'a' 'd' 'e' 'm' 'y']
<U1


In [7]:
f = np.array([100, 200, 300], dtype = np.int16)
print(f)
print(f.dtype)


[100 200 300]
int16


In [9]:
a = np.arange(20)
print(a)

b = np.arange(1, 21)
print(b)

c = np.arange(2, 41, 2)
print(c)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [10]:
d = np.linspace(0, 10, 5)
print(d)


[ 0.   2.5  5.   7.5 10. ]


In [14]:
d = np.linspace(0, 123, 9)
print(d)
print(d.dtype)

[  0.     15.375  30.75   46.125  61.5    76.875  92.25  107.625 123.   ]
float64


In [16]:
e = np.empty(5)
print(e)


[ 0.   2.5  5.   7.5 10. ]


In [18]:
f = np.zeros(5)
print(f)

[0. 0. 0. 0. 0.]


In [19]:
f = np.ones(5)
print(f)

[1. 1. 1. 1. 1.]


In [20]:
f = np.twos(5)
print(f)

AttributeError: module 'numpy' has no attribute 'twos'

In [21]:
f = np.random.rand(5)
print(f)

[0.00361063 0.30313388 0.78331633 0.69103523 0.78021704]


In [22]:
a = np.array([[1, 2, 3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [45]:
a = np.arange(1, 21)
b=a.reshape(4,5)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [49]:
c = np.arange(1,21).reshape(4,5)
d = c.flatten()
print(c)
print(d)

e = c.ravel()

print(c)
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [53]:
a = np.arange(1,101).reshape(10,10)
print(a[0,0])
print(a[1,1])
print("---------------------------------------------")
print(a[1:3, 1:3])
print("---------------------------------------------")
print(a[1:5:3, 1:5:3])
print("---------------------------------------------")
print(a[:5, :5])
print("---------------------------------------------")
print(a[7:, 7:])
print("---------------------------------------------")
print(a[::3,::3])
print("---------------------------------------------")
print(a[:,:])

1
12
---------------------------------------------
[[12 13]
 [22 23]]
---------------------------------------------
[[12 15]
 [42 45]]
---------------------------------------------
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]
---------------------------------------------
[[ 78  79  80]
 [ 88  89  90]
 [ 98  99 100]]
---------------------------------------------
[[  1   4   7  10]
 [ 31  34  37  40]
 [ 61  64  67  70]
 [ 91  94  97 100]]
---------------------------------------------
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [54]:
a=np.arange(1,20)
a=np.append(a,20)
a=np.append(a,(21,22,23,24))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [55]:
b = np.arange(1,6)
b = np.insert(b,1,6)
b = np.insert(b, 3, (7, 8))
print(b)

[1 6 2 7 8 3 4 5]


In [3]:
a = np.arange(1,7)
print(a)

[1 2 3 4 5 6]


In [8]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
print(a)
print(b)
print("-----------------------------------------")
print(b + a)
print(b - a)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
-----------------------------------------
[[ 8 10 12]
 [14 16 18]]
[[6 6 6]
 [6 6 6]]


In [11]:
a = np.random.rand(5)
print(a)

a = a * 6 + 1

print(a)

print(np.array(np.floor(a), dtype=np.int64))
print(np.array(np.ceil(a), dtype=np.int64))
print(np.array(np.round(a), dtype=np.int64))


[0.70131592 0.31179712 0.58731807 0.25361208 0.58049418]
[5.20789552 2.87078275 4.52390841 2.52167246 4.48296508]
[5 2 4 2 4]
[6 3 5 3 5]
[5 3 5 3 4]
